variable vpc_sidr_block {}
variable subnet_sidr_block {}
variable avail_zone {}
variable env_prefix {}
variable my_ip {}
variable instance_type {}
variable public_key_location {}
variable private_key_location {}
variable image_name {}